package db_beans;
import java.io.Serializable;
import java.util.Date;

import org.nutz.dao.entity.annotation.Id;
import org.nutz.dao.entity.annotation.Table;

/**
 * Model class of db_account.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Table("db_account")
public class DbAccount implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	@Id
	private Integer id;

	/** SaleID. */
	private String saleid;

	/** paytype. */
	private String paytype;

	/** cmoney. */
	private Float cmoney;

	/** rmoney. */
	private Float rmoney;

	/** operation. */
	private String operation;

	/** creattime. */
	private Date creattime;

	/** member. */
	private Integer member;

	/** descr. */
	private String descr;

	/** tableID. */
	private Integer tableid;

	/** isnormal. */
	private Integer isnormal;

	/**
	 * Constructor.
	 */
	public DbAccount() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the SaleID.
	 * 
	 * @param saleid
	 *            SaleID
	 */
	public void setSaleid(String saleid) {
		this.saleid = saleid;
	}

	/**
	 * Get the SaleID.
	 * 
	 * @return SaleID
	 */
	public String getSaleid() {
		return this.saleid;
	}

	/**
	 * Set the paytype.
	 * 
	 * @param paytype
	 *            paytype
	 */
	public void setPaytype(String paytype) {
		this.paytype = paytype;
	}

	/**
	 * Get the paytype.
	 * 
	 * @return paytype
	 */
	public String getPaytype() {
		return this.paytype;
	}

	/**
	 * Set the cmoney.
	 * 
	 * @param cmoney
	 *            cmoney
	 */
	public void setCmoney(Float cmoney) {
		this.cmoney = cmoney;
	}

	/**
	 * Get the cmoney.
	 * 
	 * @return cmoney
	 */
	public Float getCmoney() {
		return this.cmoney;
	}

	/**
	 * Set the rmoney.
	 * 
	 * @param rmoney
	 *            rmoney
	 */
	public void setRmoney(Float rmoney) {
		this.rmoney = rmoney;
	}

	/**
	 * Get the rmoney.
	 * 
	 * @return rmoney
	 */
	public Float getRmoney() {
		return this.rmoney;
	}

	/**
	 * Set the operation.
	 * 
	 * @param operation
	 *            operation
	 */
	public void setOperation(String operation) {
		this.operation = operation;
	}

	/**
	 * Get the operation.
	 * 
	 * @return operation
	 */
	public String getOperation() {
		return this.operation;
	}

	/**
	 * Set the creattime.
	 * 
	 * @param creattime
	 *            creattime
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	/**
	 * Get the creattime.
	 * 
	 * @return creattime
	 */
	public Date getCreattime() {
		return this.creattime;
	}

	/**
	 * Set the member.
	 * 
	 * @param member
	 *            member
	 */
	public void setMember(Integer member) {
		this.member = member;
	}

	/**
	 * Get the member.
	 * 
	 * @return member
	 */
	public Integer getMember() {
		return this.member;
	}

	/**
	 * Set the descr.
	 * 
	 * @param descr
	 *            descr
	 */
	public void setDescr(String descr) {
		this.descr = descr;
	}

	/**
	 * Get the descr.
	 * 
	 * @return descr
	 */
	public String getDescr() {
		return this.descr;
	}

	/**
	 * Set the tableID.
	 * 
	 * @param tableid
	 *            tableID
	 */
	public void setTableid(Integer tableid) {
		this.tableid = tableid;
	}

	/**
	 * Get the tableID.
	 * 
	 * @return tableID
	 */
	public Integer getTableid() {
		return this.tableid;
	}

	/**
	 * Set the isnormal.
	 * 
	 * @param isnormal
	 *            isnormal
	 */
	public void setIsnormal(Integer isnormal) {
		this.isnormal = isnormal;
	}

	/**
	 * Get the isnormal.
	 * 
	 * @return isnormal
	 */
	public Integer getIsnormal() {
		return this.isnormal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DbAccount other = (DbAccount) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
