package db_beans;
import java.io.Serializable;

import org.nutz.dao.entity.annotation.Id;
import org.nutz.dao.entity.annotation.Table;

/**
 * Model class of db_goods.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Table("db_goods")
public class DbGoods implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	@Id
	private Integer id;

	/** name. */
	private String name;

	/** sort. */
	private String sort;

	/** supplyID. */
	private Integer supplyid;

	/** barcode. */
	private String barcode;

	/** picaddr. */
	private String picaddr;

	/** surplus. */
	private Integer surplus;

	/** desrc. */
	private String desrc;

	/** logo. */
	private String logo;

	/** mprice. */
	private Float mprice;

	/** bprice. */
	private Float bprice;

	/** rate. */
	private Float rate;

	/** classname. */
	private String classname;

	/** validity. */
	private Integer validity;

	/**
	 * Constructor.
	 */
	public DbGoods() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the sort.
	 * 
	 * @param sort
	 *            sort
	 */
	public void setSort(String sort) {
		this.sort = sort;
	}

	/**
	 * Get the sort.
	 * 
	 * @return sort
	 */
	public String getSort() {
		return this.sort;
	}

	/**
	 * Set the supplyID.
	 * 
	 * @param supplyid
	 *            supplyID
	 */
	public void setSupplyid(Integer supplyid) {
		this.supplyid = supplyid;
	}

	/**
	 * Get the supplyID.
	 * 
	 * @return supplyID
	 */
	public Integer getSupplyid() {
		return this.supplyid;
	}

	/**
	 * Set the barcode.
	 * 
	 * @param barcode
	 *            barcode
	 */
	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	/**
	 * Get the barcode.
	 * 
	 * @return barcode
	 */
	public String getBarcode() {
		return this.barcode;
	}

	/**
	 * Set the picaddr.
	 * 
	 * @param picaddr
	 *            picaddr
	 */
	public void setPicaddr(String picaddr) {
		this.picaddr = picaddr;
	}

	/**
	 * Get the picaddr.
	 * 
	 * @return picaddr
	 */
	public String getPicaddr() {
		return this.picaddr;
	}

	/**
	 * Set the surplus.
	 * 
	 * @param surplus
	 *            surplus
	 */
	public void setSurplus(Integer surplus) {
		this.surplus = surplus;
	}

	/**
	 * Get the surplus.
	 * 
	 * @return surplus
	 */
	public Integer getSurplus() {
		return this.surplus;
	}

	/**
	 * Set the desrc.
	 * 
	 * @param desrc
	 *            desrc
	 */
	public void setDesrc(String desrc) {
		this.desrc = desrc;
	}

	/**
	 * Get the desrc.
	 * 
	 * @return desrc
	 */
	public String getDesrc() {
		return this.desrc;
	}

	/**
	 * Set the logo.
	 * 
	 * @param logo
	 *            logo
	 */
	public void setLogo(String logo) {
		this.logo = logo;
	}

	/**
	 * Get the logo.
	 * 
	 * @return logo
	 */
	public String getLogo() {
		return this.logo;
	}

	/**
	 * Set the mprice.
	 * 
	 * @param mprice
	 *            mprice
	 */
	public void setMprice(Float mprice) {
		this.mprice = mprice;
	}

	/**
	 * Get the mprice.
	 * 
	 * @return mprice
	 */
	public Float getMprice() {
		return this.mprice;
	}

	/**
	 * Set the bprice.
	 * 
	 * @param bprice
	 *            bprice
	 */
	public void setBprice(Float bprice) {
		this.bprice = bprice;
	}

	/**
	 * Get the bprice.
	 * 
	 * @return bprice
	 */
	public Float getBprice() {
		return this.bprice;
	}

	/**
	 * Set the rate.
	 * 
	 * @param rate
	 *            rate
	 */
	public void setRate(Float rate) {
		this.rate = rate;
	}

	/**
	 * Get the rate.
	 * 
	 * @return rate
	 */
	public Float getRate() {
		return this.rate;
	}

	/**
	 * Set the classname.
	 * 
	 * @param classname
	 *            classname
	 */
	public void setClassname(String classname) {
		this.classname = classname;
	}

	/**
	 * Get the classname.
	 * 
	 * @return classname
	 */
	public String getClassname() {
		return this.classname;
	}

	/**
	 * Set the validity.
	 * 
	 * @param validity
	 *            validity
	 */
	public void setValidity(Integer validity) {
		this.validity = validity;
	}

	/**
	 * Get the validity.
	 * 
	 * @return validity
	 */
	public Integer getValidity() {
		return this.validity;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DbGoods other = (DbGoods) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
