package db_beans;
import java.io.Serializable;
import java.util.Date;

/**
 * Model class of db_order.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class DbOrder implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Integer id;
	
	private int State;

	/** MemberID. */
	private Integer memberid;

	/** OrderType. */
	private String ordertype;

	/** TableID. */
	private Integer tableid;

	/** OrderName. */
	private String ordername;

	/** OrderPhone. */
	private String orderphone;

	/** People. */
	private Integer people;

	/** OrderTime. */
	private Date ordertime;

	/** HoldTime. */
	private Date holdtime;

	/** OrderLevel. */
	private Integer orderlevel;

	/** Operater. */
	private  String operater;

	/** Prepay. */
	private Float prepay;

	/** CreateTime. */
	private Date createtime;

	/**
	 * Constructor.
	 */
	public DbOrder() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the MemberID.
	 * 
	 * @param memberid
	 *            MemberID
	 */
	public void setMemberid(Integer memberid) {
		this.memberid = memberid;
	}

	/**
	 * Get the MemberID.
	 * 
	 * @return MemberID
	 */
	public Integer getMemberid() {
		return this.memberid;
	}

	/**
	 * Set the OrderType.
	 * 
	 * @param ordertype
	 *            OrderType
	 */
	public void setOrdertype(String ordertype) {
		this.ordertype = ordertype;
	}

	/**
	 * Get the OrderType.
	 * 
	 * @return OrderType
	 */
	public String getOrdertype() {
		return this.ordertype;
	}

	/**
	 * Set the TableID.
	 * 
	 * @param tableid
	 *            TableID
	 */
	public void setTableid(Integer tableid) {
		this.tableid = tableid;
	}

	/**
	 * Get the TableID.
	 * 
	 * @return TableID
	 */
	public Integer getTableid() {
		return this.tableid;
	}

	/**
	 * Set the OrderName.
	 * 
	 * @param ordername
	 *            OrderName
	 */
	public void setOrdername(String ordername) {
		this.ordername = ordername;
	}

	/**
	 * Get the OrderName.
	 * 
	 * @return OrderName
	 */
	public String getOrdername() {
		return this.ordername;
	}

	/**
	 * Set the OrderPhone.
	 * 
	 * @param orderphone
	 *            OrderPhone
	 */
	public void setOrderphone(String orderphone) {
		this.orderphone = orderphone;
	}

	/**
	 * Get the OrderPhone.
	 * 
	 * @return OrderPhone
	 */
	public String getOrderphone() {
		return this.orderphone;
	}

	/**
	 * Set the People.
	 * 
	 * @param people
	 *            People
	 */
	public void setPeople(Integer people) {
		this.people = people;
	}

	/**
	 * Get the People.
	 * 
	 * @return People
	 */
	public Integer getPeople() {
		return this.people;
	}

	/**
	 * Set the OrderTime.
	 * 
	 * @param ordertime
	 *            OrderTime
	 */
	public void setOrdertime(Date ordertime) {
		this.ordertime = ordertime;
	}

	/**
	 * Get the OrderTime.
	 * 
	 * @return OrderTime
	 */
	public Date getOrdertime() {
		return this.ordertime;
	}

	/**
	 * Set the HoldTime.
	 * 
	 * @param holdtime
	 *            HoldTime
	 */
	public void setHoldtime(Date holdtime) {
		this.holdtime = holdtime;
	}

	/**
	 * Get the HoldTime.
	 * 
	 * @return HoldTime
	 */
	public Date getHoldtime() {
		return this.holdtime;
	}

	/**
	 * Set the OrderLevel.
	 * 
	 * @param orderlevel
	 *            OrderLevel
	 */
	public void setOrderlevel(Integer orderlevel) {
		this.orderlevel = orderlevel;
	}

	/**
	 * Get the OrderLevel.
	 * 
	 * @return OrderLevel
	 */
	public Integer getOrderlevel() {
		return this.orderlevel;
	}

	/**
	 * Set the Operater.
	 * 
	 * @param operater
	 *            Operater
	 */
	public void setOperater(String operater) {
		this.operater = operater;
	}

	/**
	 * Get the Operater.
	 * 
	 * @return Operater
	 */
	public String getOperater() {
		return this.operater;
	}

	/**
	 * Set the Prepay.
	 * 
	 * @param prepay
	 *            Prepay
	 */
	public void setPrepay(Float prepay) {
		this.prepay = prepay;
	}

	/**
	 * Get the Prepay.
	 * 
	 * @return Prepay
	 */
	public Float getPrepay() {
		return this.prepay;
	}

	/**
	 * Set the CreateTime.
	 * 
	 * @param createtime
	 *            CreateTime
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * Get the CreateTime.
	 * 
	 * @return CreateTime
	 */
	public Date getCreatetime() {
		return this.createtime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DbOrder other = (DbOrder) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

	public int getState() {
		return State;
	}

	public void setState(int state) {
		State = state;
	}

}
