package db_beans;
import java.io.Serializable;

/**
 * Model class of db_permission.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class DbPermission implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Integer id;

	/** Type. */
	private String type;

	/** Perm_Name. */
	private String permName;

	/** Perm_Value. */
	private Integer permValue;

	/** State. */
	private int state;

	/** UserID. */
	private int userid;

	/** GroupID. */
	private Integer groupid;

	/**
	 * Constructor.
	 */
	public DbPermission() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the Type.
	 * 
	 * @param type
	 *            Type
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Get the Type.
	 * 
	 * @return Type
	 */
	public String getType() {
		return this.type;
	}

	/**
	 * Set the Perm_Name.
	 * 
	 * @param permName
	 *            Perm_Name
	 */
	public void setPermName(String permName) {
		this.permName = permName;
	}

	/**
	 * Get the Perm_Name.
	 * 
	 * @return Perm_Name
	 */
	public String getPermName() {
		return this.permName;
	}

	/**
	 * Set the Perm_Value.
	 * 
	 * @param permValue
	 *            Perm_Value
	 */
	public void setPermValue(Integer permValue) {
		this.permValue = permValue;
	}

	/**
	 * Get the Perm_Value.
	 * 
	 * @return Perm_Value
	 */
	public Integer getPermValue() {
		return this.permValue;
	}

	/**
	 * Set the State.
	 * 
	 * @param state
	 *            State
	 */
	public void setState(int state) {
		this.state = state;
	}

	/**
	 * Get the State.
	 * 
	 * @return State
	 */
	public int getState() {
		return this.state;
	}

	/**
	 * Set the UserID.
	 * 
	 * @param userid
	 *            UserID
	 */
	public void setUserid(int userid) {
		this.userid = userid;
	}

	/**
	 * Get the UserID.
	 * 
	 * @return UserID
	 */
	public int getUserid() {
		return this.userid;
	}

	/**
	 * Set the GroupID.
	 * 
	 * @param groupid
	 *            GroupID
	 */
	public void setGroupid(Integer groupid) {
		this.groupid = groupid;
	}

	/**
	 * Get the GroupID.
	 * 
	 * @return GroupID
	 */
	public Integer getGroupid() {
		return this.groupid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DbPermission other = (DbPermission) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
