package db_beans;
import java.io.Serializable;
import java.util.Date;

import org.nutz.dao.entity.annotation.Id;
import org.nutz.dao.entity.annotation.Table;

/**
 * Model class of db_sales.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Table("db_sales")
public class DbSales implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	@Id
	private Integer id;

	/** salename. */
	private String salename;

	/** bprice. */
	private Float bprice;

	/** mprice. */
	private Float mprice;

	/** quantity. */
	private Integer quantity;

	/** rmbsum. */
	private Float rmbsum;

	/** waiter. */
	private String waivter;

	/** creattime. */
	private Date creattime;

	/** state. */
	private String state;

	/**
	 * Constructor.
	 */
	
	private String SaleID;
	
	
	public String getSaleID() {
		return SaleID;
	}

	public void setSaleID(String saleID) {
		SaleID = saleID;
	}

	public DbSales() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the salename.
	 * 
	 * @param salename
	 *            salename
	 */
	public void setSalename(String salename) {
		this.salename = salename;
	}

	/**
	 * Get the salename.
	 * 
	 * @return salename
	 */
	public String getSalename() {
		return this.salename;
	}

	/**
	 * Set the bprice.
	 * 
	 * @param bprice
	 *            bprice
	 */
	public void setBprice(Float bprice) {
		this.bprice = bprice;
	}

	/**
	 * Get the bprice.
	 * 
	 * @return bprice
	 */
	public Float getBprice() {
		return this.bprice;
	}

	/**
	 * Set the mprice.
	 * 
	 * @param mprice
	 *            mprice
	 */
	public void setMprice(Float mprice) {
		this.mprice = mprice;
	}

	/**
	 * Get the mprice.
	 * 
	 * @return mprice
	 */
	public Float getMprice() {
		return this.mprice;
	}

	/**
	 * Set the quantity.
	 * 
	 * @param quantity
	 *            quantity
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * Get the quantity.
	 * 
	 * @return quantity
	 */
	public Integer getQuantity() {
		return this.quantity;
	}

	/**
	 * Set the rmbsum.
	 * 
	 * @param rmbsum
	 *            rmbsum
	 */
	public void setRmbsum(Float rmbsum) {
		this.rmbsum = rmbsum;
	}

	/**
	 * Get the rmbsum.
	 * 
	 * @return rmbsum
	 */
	public Float getRmbsum() {
		return this.rmbsum;
	}

	/**
	 * Set the waiter.
	 * 
	 * @param waivter
	 *            waiter
	 */
	public void setWaivter(String waivter) {
		this.waivter = waivter;
	}

	/**
	 * Get the waiter.
	 * 
	 * @return waiter
	 */
	public String getWaivter() {
		return this.waivter;
	}

	/**
	 * Set the creattime.
	 * 
	 * @param creattime
	 *            creattime
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	/**
	 * Get the creattime.
	 * 
	 * @return creattime
	 */
	public Date getCreattime() {
		return this.creattime;
	}

	/**
	 * Set the state.
	 * 
	 * @param state
	 *            state
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * Get the state.
	 * 
	 * @return state
	 */
	public String getState() {
		return this.state;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DbSales other = (DbSales) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
