package db_beans;
import java.io.Serializable;
import java.util.Date;

import org.nutz.dao.entity.annotation.Id;

/**
 * Model class of db_table.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class DbTable implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	@Id
	private Integer id;

	/** alias. */
	private String alias;

	/** tableName. */
	private String tablename;

	/** tableType. */
	private String tabletype;

	/** position. */
	private String position;

	/** lowestRMB. */
	private Float lowestrmb;

	/** allowPeople. */
	private Integer allowpeople;

	/** state. */
	private String state;

	/** isOrder. */
	private Integer isorder;

	/** salesID. */
	private String salesid;

	/** waiter. */
	private String waiter;

	/** prepay. */
	private Float prepay;

	/** startTime. */
	private Date starttime;

	/** finishTime. */
	private Date finishtime;

	/** desrc. */
	private String desrc;

	/** reserve. */
	private String reserve;

	/** permission. */
	private Integer permission;

	/** userID. */
	private Integer userid;

	/**
	 * Constructor.
	 */
	public DbTable() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the alias.
	 * 
	 * @param alias
	 *            alias
	 */
	public void setAlias(String alias) {
		this.alias = alias;
	}

	/**
	 * Get the alias.
	 * 
	 * @return alias
	 */
	public String getAlias() {
		return this.alias;
	}

	/**
	 * Set the tableName.
	 * 
	 * @param tablename
	 *            tableName
	 */
	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	/**
	 * Get the tableName.
	 * 
	 * @return tableName
	 */
	public String getTablename() {
		return this.tablename;
	}

	/**
	 * Set the tableType.
	 * 
	 * @param tabletype
	 *            tableType
	 */
	public void setTabletype(String tabletype) {
		this.tabletype = tabletype;
	}

	/**
	 * Get the tableType.
	 * 
	 * @return tableType
	 */
	public String getTabletype() {
		return this.tabletype;
	}

	/**
	 * Set the position.
	 * 
	 * @param position
	 *            position
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/**
	 * Get the position.
	 * 
	 * @return position
	 */
	public String getPosition() {
		return this.position;
	}

	/**
	 * Set the lowestRMB.
	 * 
	 * @param lowestrmb
	 *            lowestRMB
	 */
	public void setLowestrmb(Float lowestrmb) {
		this.lowestrmb = lowestrmb;
	}

	/**
	 * Get the lowestRMB.
	 * 
	 * @return lowestRMB
	 */
	public Float getLowestrmb() {
		return this.lowestrmb;
	}

	/**
	 * Set the allowPeople.
	 * 
	 * @param allowpeople
	 *            allowPeople
	 */
	public void setAllowpeople(Integer allowpeople) {
		this.allowpeople = allowpeople;
	}

	/**
	 * Get the allowPeople.
	 * 
	 * @return allowPeople
	 */
	public Integer getAllowpeople() {
		return this.allowpeople;
	}

	/**
	 * Set the state.
	 * 
	 * @param state
	 *            state
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * Get the state.
	 * 
	 * @return state
	 */
	public String getState() {
		return this.state;
	}

	/**
	 * Set the isOrder.
	 * 
	 * @param isorder
	 *            isOrder
	 */
	public void setIsorder(Integer isorder) {
		this.isorder = isorder;
	}

	/**
	 * Get the isOrder.
	 * 
	 * @return isOrder
	 */
	public Integer getIsorder() {
		return this.isorder;
	}

	/**
	 * Set the salesID.
	 * 
	 * @param salesid
	 *            salesID
	 */
	public void setSalesid(String salesid) {
		this.salesid = salesid;
	}

	/**
	 * Get the salesID.
	 * 
	 * @return salesID
	 */
	public String getSalesid() {
		return this.salesid;
	}

	/**
	 * Set the waiter.
	 * 
	 * @param waiter
	 *            waiter
	 */
	public void setWaiter(String waiter) {
		this.waiter = waiter;
	}

	/**
	 * Get the waiter.
	 * 
	 * @return waiter
	 */
	public String getWaiter() {
		return this.waiter;
	}

	/**
	 * Set the prepay.
	 * 
	 * @param prepay
	 *            prepay
	 */
	public void setPrepay(Float prepay) {
		this.prepay = prepay;
	}

	/**
	 * Get the prepay.
	 * 
	 * @return prepay
	 */
	public Float getPrepay() {
		return this.prepay;
	}

	/**
	 * Set the startTime.
	 * 
	 * @param starttime
	 *            startTime
	 */
	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	/**
	 * Get the startTime.
	 * 
	 * @return startTime
	 */
	public Date getStarttime() {
		return this.starttime;
	}

	/**
	 * Set the finishTime.
	 * 
	 * @param finishtime
	 *            finishTime
	 */
	public void setFinishtime(Date finishtime) {
		this.finishtime = finishtime;
	}

	/**
	 * Get the finishTime.
	 * 
	 * @return finishTime
	 */
	public Date getFinishtime() {
		return this.finishtime;
	}

	/**
	 * Set the desrc.
	 * 
	 * @param desrc
	 *            desrc
	 */
	public void setDesrc(String desrc) {
		this.desrc = desrc;
	}

	/**
	 * Get the desrc.
	 * 
	 * @return desrc
	 */
	public String getDesrc() {
		return this.desrc;
	}

	/**
	 * Set the reserve.
	 * 
	 * @param reserve
	 *            reserve
	 */
	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	/**
	 * Get the reserve.
	 * 
	 * @return reserve
	 */
	public String getReserve() {
		return this.reserve;
	}

	/**
	 * Set the permission.
	 * 
	 * @param permission
	 *            permission
	 */
	public void setPermission(Integer permission) {
		this.permission = permission;
	}

	/**
	 * Get the permission.
	 * 
	 * @return permission
	 */
	public Integer getPermission() {
		return this.permission;
	}

	/**
	 * Set the userID.
	 * 
	 * @param userid
	 *            userID
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * Get the userID.
	 * 
	 * @return userID
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DbTable other = (DbTable) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
