package db_beans;
import java.io.Serializable;
import java.util.Date;

import org.nutz.dao.entity.annotation.Table;

/**
 * Model class of db_user.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Table("db_user")
public class DbUser implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Integer id;

	/** GroupID. */
	private Integer groupid;

	/** LoginName. */
	private String loginname;

	/** LoginPWD. */
	private String loginpwd;

	/** ShowName. */
	private String showname;

	/** LoginIP. */
	private String loginip;

	/** LastTime. */
	private Date lasttime;

	/** Status. */
	private Integer status;

	/** WxID. */
	private String wxid;

	/** ContactInfo. */
	private String contactinfo;

	/** CreatTime. */
	private Date creattime;

	/** CardID. */
	private String cardid;

	/** UserType. */
	private String usertype;

	/**
	 * Constructor.
	 */
	public DbUser() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the GroupID.
	 * 
	 * @param groupid
	 *            GroupID
	 */
	public void setGroupid(Integer groupid) {
		this.groupid = groupid;
	}

	/**
	 * Get the GroupID.
	 * 
	 * @return GroupID
	 */
	public Integer getGroupid() {
		return this.groupid;
	}

	/**
	 * Set the LoginName.
	 * 
	 * @param loginname
	 *            LoginName
	 */
	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	/**
	 * Get the LoginName.
	 * 
	 * @return LoginName
	 */
	public String getLoginname() {
		return this.loginname;
	}

	/**
	 * Set the LoginPWD.
	 * 
	 * @param loginpwd
	 *            LoginPWD
	 */
	public void setLoginpwd(String loginpwd) {
		this.loginpwd = loginpwd;
	}

	/**
	 * Get the LoginPWD.
	 * 
	 * @return LoginPWD
	 */
	public String getLoginpwd() {
		return this.loginpwd;
	}

	/**
	 * Set the ShowName.
	 * 
	 * @param showname
	 *            ShowName
	 */
	public void setShowname(String showname) {
		this.showname = showname;
	}

	/**
	 * Get the ShowName.
	 * 
	 * @return ShowName
	 */
	public String getShowname() {
		return this.showname;
	}

	/**
	 * Set the LoginIP.
	 * 
	 * @param loginip
	 *            LoginIP
	 */
	public void setLoginip(String loginip) {
		this.loginip = loginip;
	}

	/**
	 * Get the LoginIP.
	 * 
	 * @return LoginIP
	 */
	public String getLoginip() {
		return this.loginip;
	}

	/**
	 * Set the LastTime.
	 * 
	 * @param lasttime
	 *            LastTime
	 */
	public void setLasttime(Date lasttime) {
		this.lasttime = lasttime;
	}

	/**
	 * Get the LastTime.
	 * 
	 * @return LastTime
	 */
	public Date getLasttime() {
		return this.lasttime;
	}

	/**
	 * Set the Status.
	 * 
	 * @param status
	 *            Status
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * Get the Status.
	 * 
	 * @return Status
	 */
	public Integer getStatus() {
		return this.status;
	}

	/**
	 * Set the WxID.
	 * 
	 * @param wxid
	 *            WxID
	 */
	public void setWxid(String wxid) {
		this.wxid = wxid;
	}

	/**
	 * Get the WxID.
	 * 
	 * @return WxID
	 */
	public String getWxid() {
		return this.wxid;
	}

	/**
	 * Set the ContactInfo.
	 * 
	 * @param contactinfo
	 *            ContactInfo
	 */
	public void setContactinfo(String contactinfo) {
		this.contactinfo = contactinfo;
	}

	/**
	 * Get the ContactInfo.
	 * 
	 * @return ContactInfo
	 */
	public String getContactinfo() {
		return this.contactinfo;
	}

	/**
	 * Set the CreatTime.
	 * 
	 * @param creattime
	 *            CreatTime
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	/**
	 * Get the CreatTime.
	 * 
	 * @return CreatTime
	 */
	public Date getCreattime() {
		return this.creattime;
	}

	/**
	 * Set the CardID.
	 * 
	 * @param cardid
	 *            CardID
	 */
	public void setCardid(String cardid) {
		this.cardid = cardid;
	}

	/**
	 * Get the CardID.
	 * 
	 * @return CardID
	 */
	public String getCardid() {
		return this.cardid;
	}

	/**
	 * Set the UserType.
	 * 
	 * @param usertype
	 *            UserType
	 */
	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	/**
	 * Get the UserType.
	 * 
	 * @return UserType
	 */
	public String getUsertype() {
		return this.usertype;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DbUser other = (DbUser) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
