package db_beans;
import java.io.Serializable;
import java.util.Date;

import org.nutz.dao.entity.annotation.Id;
import org.nutz.dao.entity.annotation.Name;
import org.nutz.dao.entity.annotation.Table;

/**
 * Model class of db_user.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Table("db_user")
public class DbUser implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	@Id
	private int id;

	/** GroupID. */
	private int groupid;

	/** LoginName. */
	@Name
	private String loginname;

	/** LoginPWD. */
	private String loginpwd;

	/** CreatTime. */
	private Date creattime;

	/** employID. */
	private int employid;

	/** LoginIP. */
	private String loginip;

	/** LastTime. */
	private Date lasttime;

	/** Status. */
	private int status;

	/**
	 * Constructor.
	 */
	private String wxID;
	public DbUser() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the GroupID.
	 * 
	 * @param groupid
	 *            GroupID
	 */
	public void setGroupid(Integer groupid) {
		this.groupid = groupid;
	}

	/**
	 * Get the GroupID.
	 * 
	 * @return GroupID
	 */
	public Integer getGroupid() {
		return this.groupid;
	}

	/**
	 * Set the LoginName.
	 * 
	 * @param loginname
	 *            LoginName
	 */
	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	/**
	 * Get the LoginName.
	 * 
	 * @return LoginName
	 */
	public String getLoginname() {
		return this.loginname;
	}

	/**
	 * Set the LoginPWD.
	 * 
	 * @param loginpwd
	 *            LoginPWD
	 */
	public void setLoginpwd(String loginpwd) {
		this.loginpwd = loginpwd;
	}

	/**
	 * Get the LoginPWD.
	 * 
	 * @return LoginPWD
	 */
	public String getLoginpwd() {
		return this.loginpwd;
	}

	/**
	 * Set the CreatTime.
	 * 
	 * @param creattime
	 *            CreatTime
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	/**
	 * Get the CreatTime.
	 * 
	 * @return CreatTime
	 */
	public Date getCreattime() {
		return this.creattime;
	}

	/**
	 * Set the employID.
	 * 
	 * @param employid
	 *            employID
	 */
	public void setEmployid(Integer employid) {
		this.employid = employid;
	}

	/**
	 * Get the employID.
	 * 
	 * @return employID
	 */
	public Integer getEmployid() {
		return this.employid;
	}

	/**
	 * Set the LoginIP.
	 * 
	 * @param loginip
	 *            LoginIP
	 */
	public void setLoginip(String loginip) {
		this.loginip = loginip;
	}

	/**
	 * Get the LoginIP.
	 * 
	 * @return LoginIP
	 */
	public String getLoginip() {
		return this.loginip;
	}

	/**
	 * Set the LastTime.
	 * 
	 * @param lasttime
	 *            LastTime
	 */
	public void setLasttime(Date lasttime) {
		this.lasttime = lasttime;
	}

	/**
	 * Get the LastTime.
	 * 
	 * @return LastTime
	 */
	public Date getLasttime() {
		return this.lasttime;
	}

	/**
	 * Set the Status.
	 * 
	 * @param status
	 *            Status
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * Get the Status.
	 * 
	 * @return Status
	 */
	public Integer getStatus() {
		return this.status;
	}

	public String getWxID() {
		return wxID;
	}

	public void setWxID(String wxID) {
		this.wxID = wxID;
	}



}
